### ISSUE TITLE
Network Error : Web page can not be jumped

### ISSUE THREAD

**Issue by Shaun-Fong** [game-ci/unity-license-activate#75]
![error](https://user-images.githubusercontent.com/16713354/211218312-d4199bc6-0abe-4040-9ab0-7a2e2f59564a.png)

TimeoutError: waiting for selector "#new_conversations_create_session_form #conversations_create_session_form_password" failed: timeout 30000ms exceeded
    at new WaitTask (/node/node_modules/puppeteer/lib/DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (/node/node_modules/puppeteer/lib/DOMWorld.js:478:22)
    at DOMWorld.waitForSelector (/node/node_modules/puppeteer/lib/DOMWorld.js:432:17)
    at Frame.waitForSelector (/node/node_modules/puppeteer/lib/FrameManager.js:627:47)
    at Frame.<anonymous> (/node/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.waitForSelector (/node/node_modules/puppeteer/lib/Page.js:1125:29)
    at Object.start (/node/node_modules/unity-license-activate/lib/activate.js:53:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[ERROR] Something went wrong, please check the screenshot `error.png`

**Comment by jcs090218** [comment]
There is no way to use QR code login (Connect Login) at this point, can you have your account set to Account Login?

Thanks for reporting this issue to us!

**Comment by Shaun-Fong** [comment]
> There is no way to use QR code login (Connect Login) at this point, can you have your account set to Account Login?
> 
> Thanks for reporting this issue to us!

yep.
I tried logging in with Edge and found that https://license.unity3d.com/manual didn't get to the form page, very strange.
Windows10 Edge btw.

**Comment by Shaun-Fong** [comment]
oh I think I know why . 
![image](https://user-images.githubusercontent.com/16713354/211247252-4a9c60fc-61f5-47e9-a44a-52c6add980dd.png)
There was a network error, it's weird. 
No problem after using VPN.

**Comment by Shaun-Fong** [comment]
I have confirmed the reason, it is because of the network problem that the web page can not be jumped. However, you can still jump manually by clicking the login button above, which requires additional work.

**Comment by jcs090218** [comment]
Thanks for debugging this issue! I am busy in next couple of days. If you know node.js and javascript, you can see https://github.com/game-ci/unity-license-activate/pull/71 for possible solution. The solution should be similar to the PR, and PRs are welcome! 😄

**Comment by Shaun-Fong** [comment]
@jcs090218 #77 fixed.
